# K-Nearest Neighbor

In [1]:
#Assigning features and variable
#First Features
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

In [2]:
#Second Features
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

In [3]:
#Label or target variable
play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [4]:
#Importance LabelEncoder
from sklearn import preprocessing

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [6]:
#creat labelEncoder
le = preprocessing.LabelEncoder()
#Converting string label into number
weather_encoded = le.fit_transform(weather)

In [7]:
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [8]:
temp_encoded = le.fit_transform(temp)
label_col = le.fit_transform(play)

In [9]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [10]:
label_col

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [13]:
#Combining weather and temp into single list of tuples
features = list(zip(weather_encoded,temp_encoded))

In [14]:
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [25]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)

In [26]:
#Train the model using the training set
model.fit(features,label_col)

KNeighborsClassifier(n_neighbors=3)

In [27]:
#Predict Output
Predicted = model.predict([[0,2]])

In [28]:
Predicted

array([1], dtype=int64)