In [1]:
#import Library
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('allemails.csv')

In [3]:
df

Text Spam
0     Subject: 4 color printing special  request add...    1
1     Subject: las vegas high rise boom  las vegas i...    1
2     Subject: here ' s a hot play in motion  homela...    1
3     Subject: 4 color printing special  request add...    1
4     Subject: do not have money , get software cds ...    1
...                                                 ...  ...
5731  Subject: re : research and development charges...    0
5732  Subject: re : receipts from visit  jim ,  than...    0
5733  Subject: re : enron case study update  wow ! a...    0
5734  Subject: re : interest  david ,  please , call...    0
5735  Subject: news : aurora 5 . 2 update  aurora ve...    0

[5736 rows x 2 columns]

In [4]:
df['Spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 its termination would not  have such a phenomenal impact on the power situation .  however        1
 mr suresh prabhu                                                                                  1
Name: Spam, dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

In [56]:
df

Text Spam
0     Subject: 4 color printing special  request add...    1
1     Subject: las vegas high rise boom  las vegas i...    1
2     Subject: here ' s a hot play in motion  homela...    1
4     Subject: do not have money , get software cds ...    1
5     Subject: great nnews  hello , welcome to medzo...    1
...                                                 ...  ...
5731  Subject: re : research and development charges...    0
5732  Subject: re : receipts from visit  jim ,  than...    0
5733  Subject: re : enron case study update  wow ! a...    0
5734  Subject: re : interest  david ,  please , call...    0
5735  Subject: news : aurora 5 . 2 update  aurora ve...    0

[5695 rows x 2 columns]

In [57]:
df['Spam'].value_counts()

0                                                                                               4326
1                                                                                               1364
 its termination would not  have such a phenomenal impact on the power situation .  however        1
 mr suresh prabhu                                                                                  1
Name: Spam, dtype: int64

In [58]:
df.isnull().sum()

Text    1
Spam    3
dtype: int64

In [59]:
df.dropna(subset = ['Text'], inplace = True)

In [60]:
df.isnull().sum()

Text    0
Spam    2
dtype: int64

In [61]:
df.dropna(subset = ['Spam'], inplace = True)

In [62]:
df.isnull().sum()

Text    0
Spam    0
dtype: int64

In [63]:
df

Text Spam
0     Subject: 4 color printing special  request add...    1
1     Subject: las vegas high rise boom  las vegas i...    1
2     Subject: here ' s a hot play in motion  homela...    1
4     Subject: do not have money , get software cds ...    1
5     Subject: great nnews  hello , welcome to medzo...    1
...                                                 ...  ...
5731  Subject: re : research and development charges...    0
5732  Subject: re : receipts from visit  jim ,  than...    0
5733  Subject: re : enron case study update  wow ! a...    0
5734  Subject: re : interest  david ,  please , call...    0
5735  Subject: news : aurora 5 . 2 update  aurora ve...    0

[5692 rows x 2 columns]

# Separate X and Y

In [64]:
x = df.Text.values

In [65]:
y = df.Spam.values

In [66]:
x

array(['Subject: 4 color printing special  request additional information now ! click here  click here for a printable version of our order form ( pdf format )  phone : ( 626 ) 338 - 8090 fax : ( 626 ) 338 - 8102 e - mail : ramsey @ goldengraphix . com  request additional information now ! click here  click here for a printable version of our order form ( pdf format )  golden graphix & printing 5110 azusa canyon rd . irwindale , ca 91706 this e - mail message is an advertisement and / or solicitation . ',
       "Subject: las vegas high rise boom  las vegas is fast becoming a major metropolitan city ! 60 +  new high rise towers are expected to be built on and around the las vegas strip  within the next 3 - 4 years , that ' s 30 , 000 + condominiums !  this boom has just begun ! buy first . . . early phase ,  pre - construction pricing is now available on las vegas high rises including  trump , cosmopolitan , mgm , turnberry , icon , sky , among others .  join the interest list :  http 

In [67]:
y

array(['1', '1', '1', ..., '0', '0', '0'], dtype=object)

# Split Dataset

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2)

# Data Preprocessing

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

In [71]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [72]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML Algorithm

In [73]:
from sklearn.naive_bayes import MultinomialNB

In [74]:
model = MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [75]:
x_test = cv.transform(xtest)

In [76]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [77]:
model.score(x_test, ytest)

0.9850746268656716

In [78]:
emails = ['Hey I am looking for machine language tutorial in Bangli language','hey you win an iphone x giveaway for free please do the survey','I am not Little boy', 'You win 100000 Taka a Lottery']

In [79]:
cv_emails = cv.transform(emails)

In [80]:
model.predict(cv_emails)

array(['0', '1', '0', '1'], dtype='<U92')

# Performance

In [81]:
pred = model.predict(x_test)

In [82]:
pred

array(['0', '0', '0', ..., '0', '0', '0'], dtype='<U92')

In [83]:
from sklearn.metrics import accuracy_score

In [84]:
accuracy_score(ytest,pred)

0.9850746268656716

In [85]:
from sklearn.metrics import confusion_matrix

In [86]:
confusion_matrix(ytest, pred)

array([[819,  10],
       [  7, 303]], dtype=int64)

In [87]:
from sklearn.metrics import classification_report

In [88]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       829
           1       0.97      0.98      0.97       310

    accuracy                           0.99      1139
   macro avg       0.98      0.98      0.98      1139
weighted avg       0.99      0.99      0.99      1139

